---
- hosts: all

  roles:
  - { role: "greenlab" }
  - { role: "aide-host" }
  - { role: redhataccess.redhat-access-insights-client, when: ansible_os_family == 'RedHat' }
  - { role: Stouts.postfix }
  - { role: dj-wasabi.zabbix-agent }

  vars:
    postfix_relayhost: "[smtp.gmail.com]:587"
    postfix_smtp_sasl_user: "{{ greenlab_gmail_user }}"
    postfix_smtp_sasl_password: "{{ greenlab_gmail_password }}"
    postfix_mydestination: $myhostname, localhost.$mydomain, localhost
    agent_server: 192.168.1.11
    agent_serveractive: 192.168.1.11
    zabbix_repo: other
    zabbix_selinux: True
    zabbix_url: http://zabbix.atgreen.org/zabbix
    zabbix_api_user: "{{ greenlab_zabbix_api_user }}"
    zabbix_api_pass: "{{ greenlab_zabbix_api_pass }}"
    zabbix_api_create_hosts: True
    zabbix_useip: 1
    zabbix_create_host: present
    zabbix_host_groups:
      - Linux servers
    zabbix_link_templates:
      - Template OS Linux

- hosts: h[0-2].atgreen.org
  roles:
  - { role: "rhv-host" }

- hosts: all:!h[0-2].atgreen.org
  roles:
  - { role: "rhv-guest" }

- hosts: all:!satellite.atgreen.org
  roles:
  - { role: "foreman-scap-client" }

- hosts: jumpbox.atgreen.org
  roles:
  - { role: "jumpbox" }

- hosts: devbox.atgreen.org
  roles:
  - { role: "devbox" }

- hosts: elk.atgreen.org
  roles:
  - { role: elasticsearch }
  - { role: logstash }
  - { role: nginx }
  - { role: kibana }
  - { role: instructions }

- hosts: all:!elk.atgreen.org
  roles:
  - { role: filebeat }
  
# Example of how to install Bacula on a single host
- name: Bacula all-in-one
  hosts: bacula.atgreen.org
  vars:
    # Run client on the same host like the Bacula Director
    my_client: localhost.localdomain
    my_bacula_director_clients:
      - host: "{{ my_client }}"
        password: "{{ greenlab_bacula_password }}"
        file_retention: 30 days
        jobdefs: Default
    # Client
    bacula_client_config_filedaemon_options_name: "{{ my_client }}-fd"
    # Director
    bacula_director_config_schedule:
      - Schedule:
        - Name = Daily
        - Run = Full sun at 23:10
        - Run = Incremental mon-sat at 23:10
    bacula_director_config_fileset:
      - FileSet:
        - Name = Home
        - Include:
          - File = /home
        - Exclude:
          - File = /home/nobody
    bacula_director_config_jobdefs:
      - JobDefs:
        - Name = Default
        - Type = Backup
        - Level = Incremental
        - FileSet = Home
        - Messages = Standard
        - Pool = File
        - Storage = File
        - Schedule = Daily
    bacula_director_config_job:
      - template:
          - Job:
            - Name = Job-{[{ item['jobdefs'] }]}-{[{ item['host'] }]}
            - Client = {[{ item['host'] }]}-fd
            - JobDefs = {[{ item['jobdefs'] }]}
        items: "{{ my_bacula_director_clients }}"
    bacula_director_config_client:
      - template:
          - Client:
            - Name = {[{ item['host'] }]}-fd
            - Address = {[{ item['host'] }]}
            - FD Port = 9102
            - Catalog = Default
            - Password = {[{ item['password'] }]}
            - File Retention = {[{ item['file_retention'] }]}
            - Job Retention = 3 months
            - AutoPrune = yes
        items: "{{ my_bacula_director_clients }}"
  roles:
    - role: postgresql
      tags: postgresql
    - role: jtyr.bacula_console
      tags: bacula_console
    - role: jtyr.bacula_storage
      tags: bacula_storage
    - role: jtyr.bacula_client
      tags: bacula_client
    - role: jtyr.bacula_director
      tags: bacula_director


