---
- hosts: all

  roles:
  - { role: "greenlab" }
  - { role: redhataccess.redhat-access-insights-client, when: ansible_os_family == 'RedHat' }
  - { role: Stouts.postfix }

  vars:
    postfix_relayhost: "[smtp.gmail.com]:587"
    postfix_smtp_sasl_user: "{{ greenlab_gmail_user }}"
    postfix_smtp_sasl_password: "{{ greenlab_gmail_password }}"
    postfix_mydestination: $myhostname, localhost.$mydomain, localhost

- hosts: rhv-hosts
  roles:
  - { role: "rhv-hosts" }
