---
- hosts: all

  roles:
  - { role: "greenlab" }
  - { role: redhataccess.redhat-access-insights-client, when: ansible_os_family == 'RedHat' }
  - { role: Stouts.postfix }
  - { role: dj-wasabi.zabbix-agent }

  vars:
    postfix_relayhost: "[smtp.gmail.com]:587"
    postfix_smtp_sasl_user: "{{ greenlab_gmail_user }}"
    postfix_smtp_sasl_password: "{{ greenlab_gmail_password }}"
    postfix_mydestination: $myhostname, localhost.$mydomain, localhost
    agent_server: 192.168.1.11
    agent_serveractive: 192.168.1.11
    zabbix_repo: other
    zabbix_selinux: True
    zabbix_url: http://zabbix.atgreen.org/zabbix
    zabbix_api_user: "{{ greenlab_zabbix_api_user }}"
    zabbix_api_pass: "{{ greenlab_zabbix_api_pass }}"
    zabbix_api_create_hosts: True
    zabbix_useip: 1
    zabbix_create_host: present
    zabbix_host_groups:
      - Linux servers
    zabbix_link_templates:
      - Template OS Linux

- hosts: h0.atgreen.org h1.atgreen.org h2.atgreen.org
  roles:
  - { role: "rhv-host" }

- hosts: rhv-guests
  roles:
  - { role: "rhv-guest" }

- hosts: jumpbox.atgreen.org
  roles:
  - { role: "jumpbox" }

- hosts: devbox.atgreen.org
  roles:
  - { role: "devbox" }

- hosts: elk.atgreen.org
  roles:
  - { role: elasticsearch }
  - { role: logstash }
  - { role: nginx }
  - { role: kibana }
  - { role: instructions }

- hosts: all:!elk.atgreen.org
  roles:
  - { role: filebeat }
  
