---
  - name: install additional packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - rubygem-foreman_scap_client
      - openscap-utils
      - scap-security-guide

  - name: copy config file
    copy: src=config.yaml
          dest=/etc/foreman_scap_client/config.yaml
          owner=root
          group=root
          mode=0644
