---
  - name: install the latest versions of software
    yum: name=* state=latest

  - name: install additional packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - tuned

  - name: install katello-agent
    when: inventory_hostname = "satellite.atgreen.org"
    copy: src=zabbix.repo dest=/etc/yum.repos.d/zabbix.repo

  - name: install katello-agent
    yum: pkg=katello-agent
         state=present


