---
  - name: refresh subscription info
    command: subscription-manager refresh

  - name: always make sure we're using the latest yum first
    yum: name=yum update_cache=yes state=latest

  - name: install the latest versions of software
    yum: name=* state=latest

  - name: install additional packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - tuned
      - policycoreutils-python
      - python2-pip
      - rear
      # these two are required by rear (missing dependencies)
      - efibootmgr
      - dosfstools
      # these are required by postfix to talk to gmail
      - cyrus-sasl
      - cyrus-sasl-lib
      - cyrus-sasl-plain

  - name: configure the zabbix repo for the satellite host
    when: inventory_hostname == "satellite.atgreen.org"
    copy: src=zabbix.repo dest=/etc/yum.repos.d/zabbix.repo

  - name: install katello-agent
    when: inventory_hostname != "satellite.atgreen.org"
    yum: pkg=katello-agent
         state=present

  - name: install additional satellite packages
    when: inventory_hostname == "satellite.atgreen.org"
    yum: pkg={{ item }}
         state=present
    with_items:
      - puppet-foreman_scap_client

  - name: pip install zabbix-api
    pip: name=zabbix-api

  - name: Open the zabbix agent port
    firewalld: port=10050/tcp permanent=true state=enabled
    notify: reload firewalld
