---
  - name: Install zabbix-agent
    yum: name=zabbix-agent state=present

  - name: Copy config file
    copy: src=zabbix-greenlab.conf dest=/etc/zabbix/zabbix_agentd.d/zabbix-greenlab.conf

  - name: Start and enable zabbix-agent
    service: name=zabbix-agent state=started enabled=yes

  - name: Open the zabbix agent port
    firewalld: port=10050/tcp permanent=true state=enabled
    notify: reload firewalld

  - name: Put the zabbix agent in permissive mode
    selinux_permissive: name=zabbix_agent_t permissive=true
