---
  - name: install additional packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - diffutils
      - m4
      - openssh
      - openssh-clients
      - screen
      - wget
      - ant
      - autoconf
      - automake
      - bison
      - boost-devel
      - ccache
      - createrepo
      - cvs
      - dejagnu
      - flex
      - gcc
      - gcc-c++
      - gdb
      - gettext
      - git
      - gmp-devel
      - gtkwave
      - libtool
      - make
      - mlocate
      - mock
      - patch
      - pcre-devel
      - python-devel
      - qt-devel
      - readline-devel
      - rpm-build
      - sbcl
      - sqlite-devel
      - subversion
      - tcplay
      - texinfo
      - v8-devel
      - valgrind
      - xorg-x11-fonts-100dpi
      - xorg-x11-fonts-ISO8859-1-100dpi
      - xorg-x11-fonts-ISO8859-14-100dpi
      - xorg-x11-fonts-ISO8859-2-100dpi
      - xorg-x11-fonts-ISO8859-9-100dpi
      - xorg-x11-server-utils
      - xorg-x11-xauth
      - zlib-devel
