---
  - name: add Emacs 24.4 copr repo
    yum_repository:
      name: shassard-emacs
      description: Copr repo for emacs owned by shassard
      baseurl: https://copr-be.cloud.fedoraproject.org/results/shassard/emacs/epel-7-$basearch/
      skip_if_unavailable: true
      gpgcheck: yes
      gpgkey: https://copr-be.cloud.fedoraproject.org/results/shassard/emacs/pubkey.gpg
      repo_gpgcheck: no
      enabled: yes

  - name: install additional packages
    yum: pkg={{ item }}
         state=present
    with_items:
      - ant
      - autoconf
      - automake
      - bison
      - boost-devel
      - ccache
      - createrepo
      - cvs
      - dejagnu
      - diffutils
      - duplicity
      - emacs
      - flex
      - gcc
      - gcc-c++
      - gdb
      - gettext
      - git
      - gmp-devel
      - gtkwave
      - ledger
      - libmpc-devel
      - libtool
      - m4
      - make
      - mlocate
      - mock
      - mpfr-devel
      - openssh
      - openssh-clients
      - patch
      - pcre-devel
      - python-devel
      - qt-devel
      - readline-devel
      - rear
      - rpm-build
      - sbcl
      - screen
      - sqlite-devel
      - subversion
      - texinfo
      - valgrind
      - wget
      - xorg-x11-fonts-100dpi
      - xorg-x11-fonts-ISO8859-1-100dpi
      - xorg-x11-fonts-ISO8859-14-100dpi
      - xorg-x11-fonts-ISO8859-2-100dpi
      - xorg-x11-fonts-ISO8859-9-100dpi
      - xorg-x11-server-utils
      - xorg-x11-xauth
      - zlib-devel
