---
- name: distribute rear local.conf file
  template: src=local.conf.j2
            dest=/etc/rear/local.conf
            owner=root
            group=root
            mode=0644

- name: run backup
  command: rear -d -v mkbackup
