---
- name: distribute rear local.conf file
  template: src=local.conf.j2
            dest=/etc/rear/local.conf
            owner=root
            group=root
            mode=0644

- name: run backup
  command: ionice -c2 -n7 nice -n19 rear -D -d -v mkbackup

- name: find stray rear temp files to delete
  find:
    paths: "/tmp"
    file_type: directory
    patterns: "rear.*"
  register: wildcard_dirs_to_delete

- name: delete stray temp files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ wildcard_dirs_to_delete }}"
