---
- name: mount backup filesystem
  mount: fstype=nfs path=/mnt src='192.168.1.127:/volume2/backup' state=mounted
  notify: unmount backup filesystem

- name: run engine-backup
  command: engine-backup --mode=backup --scope=all --file="/mnt/rhvm/engine-backup-$(date +%Y%m%d%H%M%S).tar.bz2" --log=/var/log/ovirt-engine-backups.log




